version: '2'

services:
  integration-tester:
    build: .
    links:
      - auth
      - rethinkdb
    environment:
      - JWT_SECRET=secret
  auth:
    build: ../..
    command: npm start -- --port 8080
    environment:
      - RETHINKDB_SERVICE_HOST=rethinkdb
      - RETHINKDB_SERVICE_PORT=28015
      - JWT_SECRET=secret
    links:
      - rethinkdb
    expose:
      - "8080"
  rethinkdb:
    image: rethinkdb
    expose:
      - "28015"
