apiVersion: v1
kind: ReplicationController
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    role: backend
    app: auth
    version: 0.0.1
  template:
    metadata:
      labels:
        role: backend
        app: auth
        version: 0.0.1
    spec:
      volumes:
      - name: secrets # SEE: http://kubernetes.io/docs/user-guide/secrets/
        secret:
          secretName: secrets
      containers:
        - name: auth
          image: hharnisc/auth
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
          ports:
            - containerPort: 9090
