apiVersion: v1
kind: ReplicationController
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    role: backend
    app: auth
    version: 0.0.1
  template:
    metadata:
      labels:
        role: backend
        app: auth
        version: 0.0.1
    spec:
      containers:
        - name: auth
          image: hharnisc/auth
          ports:
            - containerPort: 8080
